resolver: {{ cookiecutter.stack_resolver }}

packages:
  - {{ cookiecutter.project_name }}-api
  - {{ cookiecutter.project_name }}-server

extra-deps:
  - logging-effect-1.1.0
  - servant-quickcheck-0.0.2.1
