name: {{ cookiecutter.project_name }}
version: 0.1.0
synopsis: {{ cookiecutter.synopsis }}
description: Please see README.md
maintainer: {{ cookiecutter.full_name }} <{{ cookiecutter.email }}>
license: Apache
github: {{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
category: {{ cookiecutter.category }}

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - http-media
    - http-types
    - logging-effect
    - neat-interpolation
    - optparse-applicative
    - prometheus-client
    - prometheus-metrics-ghc
    - servant-server
    - time
    - wai
    - wai-extra
    - wai-middleware-prometheus
    - warp
    - wl-pprint-text

executables:
  {{ cookiecutter.project_name }}:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - {{ cookiecutter.project_name }}

tests:
  {{ cookiecutter.project_name }}-tests:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - {{ cookiecutter.project_name }}
      - tasty
