name: hello-prometheus-haskell
version: 0.1.0
synopsis: Demonstration of Prometheus instrumentation with Haskell
description: Please see README.md
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/hello-prometheus-haskell
category: Web

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - http-media
    - http-types
    - logging-effect
    - neat-interpolation
    - prometheus-client
    - prometheus-metrics-ghc
    - random
    - servant-server
    - time
    - wai
    - wai-extra
    - wai-middleware-prometheus
    - warp
    - wl-pprint-text

executables:
  hello-prometheus-haskell:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - hello-prometheus-haskell

tests:
  hello-prometheus-haskell-tests:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - hello-prometheus-haskell
      - tasty
