name: {{ cookiecutter.project_name }}-api
version: 0.1.0
synopsis: {{ cookiecutter.synopsis }}
description: Please see README.md
maintainer: {{ cookiecutter.full_name }} <{{ cookiecutter.email }}>
license: Apache
github: {{ cookiecutter.github_username }}/{{ cookiecutter.project_name }}
category: {{ cookiecutter.category }}

ghc-options: -Wall -Werror
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - http-media
    - neat-interpolation
    - servant

tests:
  {{ cookiecutter.project_name }}-api-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - {{ cookiecutter.project_name }}-api
      - tasty
